services:
  app:
    build: .
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .exa.env
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "3060:3000"
    depends_on:
      - db
      - minio
    command: >
      bash -c "rm -f /app/tmp/pids/server.pid &&
      rm -rf /app/public/assets &&
      gem cleanup &&
      bundle install -j4 &&
      rails db:migrate &&
      RAILS_ENV=production rails assets:precompile &&
      rails s -b 0.0.0.0"

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .exa.env
    volumes:
      - minio-vol:/data
    ports:
      - "9060:9000"
      - "9061:9001"
    command: server /data --console-address ":9001"

  db:
    image: mariadb:latest
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .exa.env
    volumes:
      - db-vol:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .exa.env
    ports:
      - "8060:80"
    depends_on:
      - db

volumes:
  db-vol:
  minio-vol:
